gpu_id: 1
directory: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/test_logs/detailed-old_data
window_size: 60

label_train: &label_train /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/old_all_labels_train_1m_2010-10-11_2013-10-08.pkl
label_test: &label_test /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/old_all_labels_test_1m_2013-10-09_2013-10-22.pkl
weights_train: &weights_train /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/old_all_weights_train_1m_2010-10-11_2013-10-08.pkl
weights_test: &weights_test /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/old_all_weights_test_1m_2013-10-09_2013-10-22.pkl
features_train: &features_train /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/feat/old_train_1m_2010-10-11_2013-10-08.csv
features_test: &features_test /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/feat/old_test_1m_2013-10-09_2013-10-22.csv

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      fixed_time_horizon:
        train: *label_train
        test: *label_test
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      forward_looking:
        train: *weights_train
        test: *weights_test
    data:
      # Possible values: "raw", "features"
      features:
        train: *features_train
        test: *features_test
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        hyperparameters: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/hp/transformer_feat/features-fixed_time_horizon-forward_looking-transformer/best_hp.json
        batch_size: 64
        epochs: 150
        early_stopping_patience: 15
        cv_splits: 5

  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      oracle:
        train: *label_train
        test: *label_test
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      forward_looking:
        train: *weights_train
        test: *weights_test
    data:
      # Possible values: "raw", "features"
      features:
        train: *features_train
        test: *features_test
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        hyperparameters: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/hp/transformer_feat/features-oracle-forward_looking-transformer/best_hp.json
        batch_size: 64
        epochs: 150
        early_stopping_patience: 15
        cv_splits: 5
