gpu_id: 0
directory: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/test_logs/intraday_raw
window_size: 60

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      all:
        train: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/all_labels_train_1m_2010-10-11_2013-10-08.pkl
        test: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/all_labels_test_1m_2013-10-09_2013-10-22.pkl
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      trend_interval_return:
        train: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/all_weights_train_1m_2010-10-11_2013-10-08.pkl
        test: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/all_weights_test_1m_2013-10-09_2013-10-22.pkl
      forward_looking:
        train: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/all_weights_train_1m_2010-10-11_2013-10-08.pkl
        test: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/all_weights_test_1m_2013-10-09_2013-10-22.pkl
      none:
    data:
      # Possible values: "raw", "features"
      raw:
        train: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/raw/train_1m_2010-10-11_2013-10-08.csv
        test: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/raw/test_1m_2013-10-09_2013-10-22.csv
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        hyperparameters: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/transformer_raw/raw-ct_two_state-none-transformer/best_hp.json
        batch_size: 64
        epochs: 300
        early_stopping_patience: 20
        cv_splits: 5
