gpu_id: 0 # GPU ID to use; possible values: 0, 1
directory: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/transformer_raw
window_size: 60

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      all:
        path: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/all_labels_train_1m_2018-06-19_2021-07-01.pkl
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      none:
    data:
      # Possible values: "raw", "features"
      raw:
        path: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/raw/train_1m_2018-06-19_2021-07-01.csv
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        batch_size: 64
        epochs: 300
        early_stopping_patience: 30
        trial_num: 20
        initial_random_trials: 3
        cv_splits: 5 # Number of cross-validation splits, must be at least 2
