gpu_id: 0 # GPU ID to use; possible values: 0, 1
directory: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/hp/transformer_feat_big_data_drop
window_size: 60

label_common_path: &label_common_path /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/old_all_labels_train_1m_2010-10-11_2013-10-08.pkl
features_common_path: &features_common_path /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/feat/old_train_1m_2010-10-11_2013-10-08.csv
weights_common_path: &weights_common_path /home/mdzaja/MasterThesis/artifacts/assets/AAPL/weights/old_all_weights_train_1m_2010-10-11_2013-10-08.pkl

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      fixed_time_horizon:
        path: *label_common_path
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      trend_interval_return:
        path: *weights_common_path
      forward_looking:
        path: *weights_common_path
    data:
      # Possible values: "raw", "features"
      features:
        drop_duplicates:
        drop_zero_volume:
        path: *features_common_path
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        batch_size: 128
        epochs: 150
        early_stopping_patience: 30
        trial_num: 20
        initial_random_trials: 5
        cv_splits: 5 # Number of cross-validation splits, must be at least 2
  
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      fixed_time_horizon:
        path: *label_common_path
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      trend_interval_return:
        class_balance:
        path: *weights_common_path
      forward_looking:
        class_balance:
        path: *weights_common_path
    data:
      # Possible values: "raw", "features"
      features:
        drop_duplicates:
        drop_zero_volume:
        path: *features_common_path
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        batch_size: 128
        epochs: 150
        early_stopping_patience: 30
        trial_num: 20
        initial_random_trials: 5
        cv_splits: 5 # Number of cross-validation splits, must be at least 2
