gpu_id: 0 # GPU ID to use; possible values: 0, 1
directory: /home/mdzaja/MasterThesis/artifacts/assets/AAPL/models/hp/transformer_feat
window_size: 60

label_common_path: &label_common_path /home/mdzaja/MasterThesis/artifacts/assets/AAPL/labels/all_labels_train_1m_2010-10-11_2012-11-06.pkl
features_common_path: &features_common_path /home/mdzaja/MasterThesis/artifacts/assets/AAPL/data/feat/train_1m_2010-10-11_2012-11-06.csv

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      ct_two_state:
        path: *label_common_path
      ct_three_state:
        path: *label_common_path
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      none:
    data:
      # Possible values: "raw", "features"
      features:
        path: *features_common_path
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        batch_size: 128
        epochs: 150
        early_stopping_patience: 15
        trial_num: 15
        initial_random_trials: 5
        cv_splits: 5 # Number of cross-validation splits, must be at least 2
  
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      ct_two_state:
        path: *label_common_path
      ct_three_state:
        path: *label_common_path
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      none:
        class_balance:
    data:
      # Possible values: "raw", "features"
      features:
        path: *features_common_path
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      transformer:
        batch_size: 128
        epochs: 150
        early_stopping_patience: 15
        trial_num: 15
        initial_random_trials: 5
        cv_splits: 5 # Number of cross-validation splits, must be at least 2
