gpu_id: 0 # GPU ID to use; possible values: 0, 1
directory: /path/to/directory # Path to result directory

combinations:
  - labels:
      # Possible values: "all", "ct_two_state", "ct_three_state", "fixed_time_horizon", "oracle", "triple_barrier"
      ct_two_state:
        path: /path/to/ct_two_state/labels.pkl
      ct_three_state:
        path: /path/to/ct_three_state/labels.pkl
    weights:
      # Possible values: "all", "none", "trend_interval_return", "forward_looking", "sequential_return", "backward_looking"
      # "all" is equivalent to "trend_interval_return, forward_looking, sequential_return, backward_looking"
      trend_interval_return:
        path: /path/to/trend_interval_return/weights.pkl
      none:  # If 'none', no paths are required
    data:
      # Possible values: "raw", "features"
      raw:
        path: /path/to/raw/data.csv
    model:
      # Possible values: "cnn_lstm", "lstm", "transformer"
      cnn_lstm:
        batch_size: 64
        epochs: 500
        early_stopping_patience: 50
        trial_num: 100
        initial_random_trials: 10
        cv_splits: 10 # Number of cross-validation splits, must be at least 2

  # ... other combinations
